#!/usr/bin/bash

# Copyright (c) 2021 Tuncay D.
# MIT License, see LICENSE

# RETROARCH PLAYLIST EXTRACTOR

## SETTINGS

# Path to your retroarch config folder.

retroarch_dir="$HOME/.config/retroarch"

# Default filter mode, if not specified as script argument 1.
#   nofilter: do not filter the list, output every game
#   last: get top most single entry, useful in combination with history
#   dmenu: use dmenu program to create a gui and select one game
#   rofi: similar and an alternative program to dmenu

default_mode="nofilter"

## END OF SETTINGS

# Argument 1: Override default mode.

if [ ! -z "$1" ]; then
    mode="$1"
else
    mode="$default_mode"
fi

# Argument 2: Specify a playlist or default to history.

if [ ! -z "$2" ]; then

    if [[ "$2" == *.lpl  ]]; then
        playlist="$2"
    else
        playlist="$retroarch_dir/playlists/$2.lpl"
    fi

else
    playlist="$retroarch_dir/content_history.lpl"
fi

playlist="${playlist/#\~/$HOME}"
playlist=$(echo $playlist)
playlist="$(readlink -f -n "$playlist")"

# Extract all path from playlist.

games_path=$(grep -oP '(?<="path": ").*(?=",)' "$playlist")

# Add filter or a program to the chain.

case "$mode" in

    nofilter)   echo "$games_path" ;;
    last)       echo "$games_path" | head -n 1 ;;
    dmenu)      echo "$games_path" | dmenu -l 15 ;;
    rofi)       echo "$games_path" | rofi -dmenu -i ;;

esac

